# Адрес мастерноды с открытым доступом к API, по умолчанию - мастернода разработчиков Minter
address = "https://minter-node-1.testnet.minter.network"

# Адрес API движка ValidatorCenter
address_vc = "http://validator.center:4000"

# Приватные ключи аккаунта (только 1 аккаунт!)
accounts = ["Mx-вводить не нужно!","..."]

# Время ожидания между делегированием (в минутах)
timeout = 10
# Минимальная сумма делегирования
min_amount = 100